---
# defaults file for device_onboarding

devices:
  - host_name: Node-1
    connectivity_ip: 198.19.1.1
    longitude: -87.6244212
    latitude: 41.8755616
    nso_provider_name: nso201
    credential_profile: demo
  - host_name: Node-2
    connectivity_ip: 198.19.1.2
    longitude: -73.9871558
    latitude: 40.7308619
    nso_provider_name: nso201
    credential_profile: demo
  - host_name: Node-3
    connectivity_ip: 198.19.1.3
    longitude: -84.3901849
    latitude: 33.7490987
    nso_provider_name: nso201
    credential_profile: demo
  - host_name: Node-4
    connectivity_ip: 198.19.1.4
    longitude: -80.1936589
    latitude: 25.7742658
    nso_provider_name: nso201
    credential_profile: demo
  - host_name: Node-5
    connectivity_ip: 198.19.1.5
    longitude: -122.3300624
    latitude: 47.6038321
    nso_provider_name: nso201
    credential_profile: demo
  - host_name: Node-7
    connectivity_ip: 198.19.1.7
    longitude: -95.3676974
    latitude: 29.7589382
    nso_provider_name: nso201
    credential_profile: demo
  - host_name: Node-8
    connectivity_ip: 198.19.1.8
    longitude: -104.9848623
    latitude: 39.7392364
    nso_provider_name: nso201
    credential_profile: demo