---
# tasks file for enable_gnmi

# include role to gather device information

- name: get into JWT
  import_tasks: "{{playbook_dir}}/common-tasks/jwt.yml"

- name: import task to get device information from crosswork
  import_tasks: "{{playbook_dir}}/common-tasks/get_device_info_from_cnc.yml"

    
- name: admin reset (down and up)
  include_tasks: admin_reset.yml
  loop: "{{devices}}"