---

- hosts: localhost
  gather_facts: true
  connection: local
  vars_files:
    - "{{playbook_dir}}/global_variable.yml"

  roles:
    - device_onboarding
    - obtain_cdg_info
    - attach_device_to_cdg
    - enable_gnmi