---

- hosts: localhost
  gather_facts: true
  connection: local
  vars_files:
    - "{{playbook_dir}}/global_variables.yml"
    - "{{playbook_dir}}/vault_variables.yml"

  roles:
    # - device_onboarding
    # - enable_gnmi
    - attach_cdg
    