---

# pre-requsite:   jwt.yml task 
- name: get dg pool uuid
  uri:
    validate_certs: no
    status_code: [200, 201, 202]
    method: POST
    url: "https://{{cnc_ip}}:{{cnc_port}}/crosswork/dg-manager/v1/hapool/query"
    return_content: yes
    headers:
      Content-Type: application/json
      Accept: application/json
      Authorization: "Bearer {{ myJWT.content }}"
    body_format: json
    body:       
  register: dgpool_ids

- debug:
    msg: "dgpool uuid {{dgpool_ids.json.data[0]}}"
  

  
