---
# post-install/roles/dg-pools/defaults/main.yml

profiles: 
  - name: NSO
    types: 
      - type: ROBOT_USERPASS_NETCONF
      - type: ROBOT_USERPASS_HTTP
  - name: SR-PCE
    types:
      - type: ROBOT_USERPASS_HTTP
  - name: 
    hostname: lab1r00002-ne-pe1
    profile: DEVICES-LOCAL
    capabilities: '"YANG_CLI", "SNMP", "GNMI","YANG_MDT"'
    syslog_format: "RFC_5424"
    admin_state: "ROBOT_ADMIN_STATE_DOWN"
    connectivities:
      - type: ROBOT_MSVC_TRANS_SSH
        port: 22
        ip: 10.140.129.65
      - type: ROBOT_MSVC_TRANS_SNMP
        port: 161
        ip: 10.140.129.65
      - type: ROBOT_MSVC_TRANS_GNMI
        port: 57400
        ip: 10.140.129.65
        encoding: "JSON_IETF"
    streaming:
      vrf: Loopback10
    location:
      lat: 41.881832
      long: -87.623177
    providers:
      - nso: NSO

  - ip: 10.140.129.67
    type: ROBOT_INET_ADDR_TYPE_v4
    hostname: lab1r00002-ne-pe3
    profile: DEVICES-LOCAL
    capabilities: '"YANG_CLI", "SNMP", "GNMI","YANG_MDT"'
    syslog_format: "RFC_5424"
    admin_state: "ROBOT_ADMIN_STATE_DOWN"
    connectivities:
      - type: ROBOT_MSVC_TRANS_SSH
        port: 22
        ip: 10.140.129.67
      - type: ROBOT_MSVC_TRANS_SNMP
        port: 161
        ip: 10.140.129.67
      - type: ROBOT_MSVC_TRANS_GNMI
        port: 57400
        ip: 10.140.129.67
        encoding: "JSON_IETF"
    streaming:
      vrf: Loopback10
    location:
      lat: 41.881832
      long: -118.243683
    providers:
      - nso: NSO

  - ip: 10.140.129.77
    type: ROBOT_INET_ADDR_TYPE_v4
    hostname: CSR
    profile: DEVICES-LOCAL
    capabilities: '"YANG_CLI", "SNMP", "GNMI","YANG_MDT"'
    syslog_format: "RFC_5424"
    admin_state: "ROBOT_ADMIN_STATE_DOWN"
    connectivities:
      - type: ROBOT_MSVC_TRANS_SSH
        port: 22
        ip: 10.140.129.77
      - type: ROBOT_MSVC_TRANS_SNMP
        port: 161
        ip: 10.140.129.77
      - type: ROBOT_MSVC_TRANS_GNMI
        port: 57400
        ip: 10.140.129.77
        encoding: "JSON_IETF"
    streaming:
      vrf: Loopback10
    location:
      lat: 33.753746
      long: -84.38633
    providers:
      - nso: NSO

    