---
# tasks file for device_onboarding

# import a common task to do jwt
- name: get into JWT
  import_tasks: "{{playbook_dir}}/common-tasks/jwt.yml"
  
- name: invoke add nodes API using lookup template
  uri:
    validate_certs: no
    status_code: [200, 201, 202]
    method: POST
    url: "https://{{cnc_ip}}:{{cnc_port}}/crosswork/inventory/v1/nodes"
    return_content: yes
    headers:
      Content-Type: application/yang-data+json
      Accept: application/yang-data+json
      Authorization: "Bearer {{ myJWT.content }}"
    body_format: json
    body: "{{ lookup('template', 'add-device.j2') }}"
  register: addNodeAPIOoutput
  loop: "{{devices}}"
  loop_control:
    pause: 1
