---
# tasks file for obtain_cdg_info

- name: invoke API to get all CDG detail
  uri:
    validate_certs: no
    status_code: [200, 201, 202]
    method: POST
    url: "https://{{cnc_ip}}:{{cnc_port}}/crosswork/dg-manager/v1/dg/query"
    return_content: yes
    headers:
      Content-Type: application/json
      Accept: application/json
      Authorization: "Bearer {{ myJWT.content }}"
    body_format: json
    body: 
      filter:
        configData: 
          role: "ASSIGNED"
  register: cdg_detail

# - name: print cdg_detail variable type
#   debug:
#     msg: "{{ cdg_detail.json.data[0] | type_debug}}"

# - name: print cdg_detail
#   debug:
#     msg: "{{ cdg_detail }}"

- name: print a list of the CDG in Assinged Role and its vdgUuid
  debug:
    msg: "CDG name: {{ item.name }}. CDG vdgUuid: {{item.configData.vdgUuid}}"
  loop: "{{cdg_detail.json.data}}"
  when: item.configData.role == "ASSIGNED"
  # when: item.configData.vdgUuid is defined
  loop_control:
    label: "{{ item.name }}"


# Timestamp reference: https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#handling-dates-and-times
# - name: output CDG vdgUuid to a file
#   local_action:
#     module: lineinfile
#     line: "CDG name: {{ item.name }}. CDG vdgUuid: {{item.configData.vdgUuid}}"
#     path: "{{playbook_dir}}/temp_folder/obtain_cdg_info/cdg-info-{{ '%Y-%m-%d %H:%M:%S' | strftime(ansible_date_time.epoch) }}"
#     create: yes
#   loop: "{{cdg_detail.json.data}}"
#   loop_control:
#     label: "{{ item.name }}"
#   when: item.configData.role == "ASSIGNED"