---
# tasks file for enable_gnmi

# include role to gather device information

- name: get into JWT
  import_tasks: "{{playbook_dir}}/common-tasks/jwt.yml"

- name: import task to get device information from crosswork
  import_tasks: "{{playbook_dir}}/common-tasks/get_device_info_from_cnc.yml"

    
- name: attach to cdg
  import_tasks: attach_cdg.yml
  