---

- hosts: localhost
  gather_facts: true
  connection: local
  vars_files:
    - "{{playbook_dir}}/global_variables.yml"
    - "{{playbook_dir}}/vault_variables.yml"

  roles:
    # - device_onboarding
    - admin_reset
    # - attach_device_to_cdg
    #- obtain_cdg_info