---
# tasks file for enable_gnmi

# include role to gather device information

- name: import role get device loopbacks from nso
  import_role: 
    role: get_device_loopbacks_from_nso

- name: pause
  pause:
    seconds: 3

- name: import task to get device information from crosswork
  import_tasks: "{{playbook_dir}}/common-tasks/get_device_info_from_cnc.yml"

    
- name: enable gnmi
  include_tasks: enable_gnmi.yml
  loop: "{{devices}}"